# Generated by Django 4.1.2 on 2023-06-26 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripcion',
            new_name='Preparacion',
        ),
    ]
